spring.application.name=DecHelper
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.ollama.base-url=http://localhost:7869
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=qwen3:8b
#spring.ai.ollama.chat.model=llama3.1:8b
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.init.pull-model-strategy=never

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine-distance
spring.ai.vectorstore.pgvector.max-document-batch-size=100
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=true

logging.level.org.springframework.ai.chat.client=debug
# more precise debugging for request and response
#logging.level.org.springframework.ai.chat.observation=TRACE
#logging.level.org.springframework.web=trace

spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.chat.observations.include-error-logging=true

#logging.level.org.springframework.jdbc.core=trace
logging.level.org.springframework=info
#develop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
